### ISSUE TITLE
WindowsError: [Error 32] : 'run_tp.py.log'

### ISSUE THREAD

**Issue by Cute-abacus** [wsdream/AMF#2]
作者你好~我已经按照您readme中的介绍install了AMF模块，并下载好数据集，在运行请run_rt.py和run_pt.py时遇到如下报错，请问这里的WinError是什么导致的呢？我能如何处理呢？
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\CodingSoftware\ANACONDA\envs\AMF\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "D:\CodingSoftware\ANACONDA\envs\AMF\lib\multiprocessing\forking.py", line 510, in prepare
    '__parents_main__', file, path_name, etc
  File "D:\STUDY\Project\AMF\benchmarks\run_tp.py", line 39, in <module>
    utils.setConfig(para) # set configuration
  File "D:\STUDY\Project\AMF\benchmarks\commons\utils.py", line 30, in setConfig
    os.remove(config['logFile'])
WindowsError: [Error 32] : 'run_tp.py.log'
`

**Comment by aimengda** [comment]
logging error when you write log to one file from multiple processes, so you need to update the logging to let it support multiprocessing
